### PR TITLE
Make sure `elements` gets instanceName. Fix #9.

### LINKED ISSUE #9: Some objects not being created with their instance name/key
From [this object](https://github.com/plocket/al_story/files/6056873/skipped.txt), we get:
```
| your_children_past_benefits.start_date |  | 04/04/2004 |
```
instead of 
```
| your_children_past_benefits['SSI'].start_date |  | 04/04/2004 |
```

We're missing:
```json
    "benefit": {
      "_class": "docassemble.base.core.DAObject", 
      "end": "2021-02-28T00:00:00-05:00", 
      "end_date": "2021-02-28T00:00:00-05:00", 
      "instanceName": "your_children_past_benefits['SSI']", 
      "start_date": "2004-04-04T00:00:00-05:00", 
      "still_receiving": false
    }, 
```

### PR DESCRIPTION
**Pull request by plocket**
Fix #9. Test:

All you have to do to load it up is clone it and open the index.html file in your browser. (That's as sophisticated as this has gotten so far.)

Diff can be seen easily with https://www.diffchecker.com/diff.

See difference between main and this branch when processing [data](https://github.com/plocket/al_story/files/6056951/skipped.txt).

Main:
```
| your_children_past_benefits.end_date | | 02/28/2021 |
```

New:
```
| your_children_past_benefits['SSI'].end_date |  | 02/28/2021 |
```

### CODE REVIEW

**Comment by plocket** [comment]
It looks to me like now both are appearing. I'm not sure why and it shouldn't break anything I've run across so far. That's not good, but I'm also very frustrated at the moment. Maybe its' something to tackle later.

**Comment by niharikasingh** [comment]
> It looks to me like now both are appearing. I'm not sure why and it shouldn't break anything I've run across so far. That's not good, but I'm also very frustrated at the moment. Maybe its' something to tackle later.

🤔 Could both be appearing because of this object in the `skipped.txt` file? If so, I'm not sure what the best way to exclude this would be... 
```json
    "your_children_past_benefits": {
      "_class": "docassemble.base.core.DADict", 
      "ask_number": false, 
      "ask_object_type": false, 
      "auto_gather": true, 
      "complete_attribute": null, 
      "elements": {
        "SSI": {
          "_class": "docassemble.base.core.DAObject", 
          "end": "2021-02-28T00:00:00-05:00", 
          "end_date": "2021-02-28T00:00:00-05:00", 
          "instanceName": "your_children_past_benefits['SSI']", 
          "start_date": "2004-04-04T00:00:00-05:00", 
          "still_receiving": false
        }
      }, 
      "instanceName": "your_children_past_benefits", 
      "minimum_number": null, 
      "object_type": {
        "_class": "type", 
        "name": "docassemble.base.core.DAObject"
      }, 
      "object_type_parameters": {}, 
      "there_are_any": true
    }, 
```

**EDITED TO ADD**: I feel _very, very_ silly, but diff checker gives me no differences between the file generated by `main` branch and the file generated by `9_instance_name` branch, which seems wrong... I might be messing this up somehow. I'll try again with a fresh pair of eyes during study session on Friday (or maybe before then if I can steal some time).

**Comment by plocket** [comment]
You're totally on point! I'm having the same result. I'll take a close look.

**Comment by plocket** [comment]
I think I must have hallucinated. ~In that case, either this PR is to remove some unused code or this test is not sufficient to trigger the deleted code from breaking something. Close or merge or what?~

[Bleh, it adds code. I did think it was very strange that the line needed to be added. I must have done something strange with the table I was using at some point. Let's close this one? It'll be here later for reference if needed.]

**Comment by plocket** [comment]
Feel free to close if you agree with the edited comment above.

**Pull request closed without merging**
